// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvcYZisIjJvwUa-4HucahhLouolOcXj64',
    appId: '1:262974148294:web:d95e2c356bb0b8fe6911c7',
    messagingSenderId: '262974148294',
    projectId: 'forsaty-8dc9c',
    authDomain: 'forsaty-8dc9c.firebaseapp.com',
    storageBucket: 'forsaty-8dc9c.firebasestorage.app',
    measurementId: 'G-KBZYJ0FP61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl2LZhmFFHlPXezS0NaXeINWQOtj1AWr0',
    appId: '1:262974148294:android:ad31aea888f8cc466911c7',
    messagingSenderId: '262974148294',
    projectId: 'forsaty-8dc9c',
    storageBucket: 'forsaty-8dc9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPuBlS93m4whh9tp_NyvlIO7cXgBjCNI',
    appId: '1:262974148294:ios:324fd436bcc16f336911c7',
    messagingSenderId: '262974148294',
    projectId: 'forsaty-8dc9c',
    storageBucket: 'forsaty-8dc9c.firebasestorage.app',
    iosBundleId: 'com.forsaty.forsaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuPuBlS93m4whh9tp_NyvlIO7cXgBjCNI',
    appId: '1:262974148294:ios:324fd436bcc16f336911c7',
    messagingSenderId: '262974148294',
    projectId: 'forsaty-8dc9c',
    storageBucket: 'forsaty-8dc9c.firebasestorage.app',
    iosBundleId: 'com.forsaty.forsaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvcYZisIjJvwUa-4HucahhLouolOcXj64',
    appId: '1:262974148294:web:77d63bb1f72c4fc26911c7',
    messagingSenderId: '262974148294',
    projectId: 'forsaty-8dc9c',
    authDomain: 'forsaty-8dc9c.firebaseapp.com',
    storageBucket: 'forsaty-8dc9c.firebasestorage.app',
    measurementId: 'G-NZJKLWLGVJ',
  );
}
